### ISSUE TITLE
Updates for Integrity Constraints and E/R Diagram

### ISSUE THREAD

**Issue by Macinto5h** [Macinto5h/CS3600-GroupProject#2]
Our database has changed from its original framework, so at some point we'll need to make these aspects of the project concise.

**Comment by PeterSimari** [comment]
For this we need to factor in a couple things:

1. The SalesItem table must be implemented.
2. The IsReturn table must be implemented
3. CustomerId must be implemented with the Sales table
4. Password must be added to the Person table now.

5. Update Sales relation by getting rid of Total and Quantity, replace with the relations between SalesItem and IsReturn.

**Comment by Macinto5h** [comment]
Both a normalized and unnormalized diagram are now uploaded to the repository. Problem solved.
