### ISSUE TITLE
Where does the tables sit in the normalization hierarchy by applying the checking as we went through in class and described in the textbook/notes? 

### ISSUE THREAD

**Issue by Macinto5h** [Macinto5h/CS3600-GroupProject#5]

**Comment by PeterSimari** [comment]
**Current Status:**
1NF - Sales
2NF - Employee, Person, WorksIn, and Product.
3NF - Customer and Department
BCNF - 
Picture attaches is the changes we made to the Sales table. We haven't implemented it into the database yet, but that is the current plan.

![img_6901](https://user-images.githubusercontent.com/44033799/48442291-c8b2c780-e75b-11e8-8cc4-a113d7659bc0.png)
